In [1]:
import numpy as np

In [2]:
list=[1,2,3,4,5]

In [3]:
arr=np.array(list)

In [5]:
type(arr)

numpy.ndarray

In [8]:
arr

array([1, 2, 3, 4, 5])

In [6]:
arr.shape

(5,)

In [7]:
list1=[1,2,3,4,5]
list2=[5,6,7,8,9]
list3=[2,3,4,5,6]

In [9]:
arr1=np.array([list1,list2,list3])

In [10]:
arr1

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6]])

In [11]:
arr1.shape

(3, 5)

In [12]:
arr1.reshape((1,15))

array([[1, 2, 3, 4, 5, 5, 6, 7, 8, 9, 2, 3, 4, 5, 6]])

In [14]:
arr1.reshape((15,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [5],
       [6],
       [7],
       [8],
       [9],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [15]:
arr1.reshape((5,3))

array([[1, 2, 3],
       [4, 5, 5],
       [6, 7, 8],
       [9, 2, 3],
       [4, 5, 6]])

# Indexing

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
arr[3]

4

In [19]:
arr[1]

2

In [20]:
arr[1:]

array([2, 3, 4, 5])

In [21]:
arr[-1]

5

In [22]:
arr1

array([[1, 2, 3, 4, 5],
       [5, 6, 7, 8, 9],
       [2, 3, 4, 5, 6]])

In [23]:
arr1[0:2,0:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [24]:
arr1[1,2:]

array([7, 8, 9])

In [25]:
arr1[2,0:3]

array([2, 3, 4])

In [30]:
arr=np.arange(1,10)

In [31]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
arr[3:]=100

In [33]:
arr

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [34]:
arr1=arr

In [35]:
arr1[3:]=50

In [36]:
arr1

array([ 1,  2,  3, 50, 50, 50, 50, 50, 50])

In [37]:
arr

array([ 1,  2,  3, 50, 50, 50, 50, 50, 50])

In [38]:
arr1=arr.copy()

In [39]:
arr1

array([ 1,  2,  3, 50, 50, 50, 50, 50, 50])

In [40]:
arr

array([ 1,  2,  3, 50, 50, 50, 50, 50, 50])

In [41]:
arr1[3:]=100

In [42]:
arr1

array([  1,   2,   3, 100, 100, 100, 100, 100, 100])

In [43]:
arr

array([ 1,  2,  3, 50, 50, 50, 50, 50, 50])

In [45]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [51]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [52]:
## Some conditions very useful in exploratory data analysis

In [53]:
arr

array([ 1,  2,  3, 50, 50, 50, 50, 50, 50])

In [57]:
val=3
arr<val

array([ True,  True, False, False, False, False, False, False, False])

In [58]:
arr[arr<val]

array([1, 2])

In [59]:
arr=np.arange(0,10).reshape((2,5))

In [68]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [69]:
arr*2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [70]:
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [71]:
arr/2

array([[0. , 0.5, 1. , 1.5, 2. ],
       [2.5, 3. , 3.5, 4. , 4.5]])

In [72]:
arr//2

array([[0, 0, 1, 1, 2],
       [2, 3, 3, 4, 4]], dtype=int32)

In [81]:
np.ones((2,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [82]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [85]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [88]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [90]:
np.random.rand(4,5)

array([[0.91995766, 0.02596717, 0.81928412, 0.37322921, 0.81115427],
       [0.36158086, 0.44097527, 0.50463094, 0.24491038, 0.99744595],
       [0.12122538, 0.12556703, 0.64942629, 0.57298365, 0.02339706],
       [0.42112445, 0.7813441 , 0.11087452, 0.12069254, 0.67272705]])

In [91]:
np.random.randn(4,5)

array([[-4.39956417e-01,  1.14104655e+00,  9.57739455e-01,
         5.25133941e-01, -1.75650843e+00],
       [-5.52707150e-01,  1.41205526e+00, -1.78495586e+00,
         7.53112327e-01,  1.40622341e-02],
       [-6.51535294e-01, -4.86051975e-01, -6.22714105e-01,
        -1.45023267e-03, -9.31765394e-01],
       [ 1.16423218e+00, -2.93225253e-01, -8.36701317e-02,
        -7.60821035e-01,  1.37982058e-01]])

In [103]:
np.random.randint(0,10,12).reshape((3,4))

array([[4, 7, 9, 1],
       [6, 0, 9, 0],
       [4, 4, 7, 2]])

In [104]:
np.random.random_sample((2,3))

array([[0.02675049, 0.8128989 , 0.75762694],
       [0.66136328, 0.14303858, 0.79079167]])