In [1]:
import pandas as pd
import numpy as np

In [6]:
df=pd.DataFrame(np.arange(0,20).reshape(4,5),columns=["col1","col2","col3","col4","col5"],index=["row1","row2","row3","row4"])
df

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19

In [7]:
##Indexing by .loc and .iloc 

In [10]:
df.loc["row1"]

col1    0
col2    1
col3    2
col4    3
col5    4
Name: row1, dtype: int32

In [9]:
type(df.loc["row1"])

pandas.core.series.Series

In [13]:
df.loc["row1"]["col2"]

1

In [15]:
df

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19

In [16]:
df.iloc[:,:2]

col1  col2
row1     0     1
row2     5     6
row3    10    11
row4    15    16

In [21]:
df.iloc[:2,0]

row1    0
row2    5
Name: col1, dtype: int32

In [22]:
type(df.iloc[:2,0])

pandas.core.series.Series

In [23]:
df.iloc[:,1:]

col2  col3  col4  col5
row1     1     2     3     4
row2     6     7     8     9
row3    11    12    13    14
row4    16    17    18    19

In [28]:
##Converting Dataframes into arrays
df

col1  col2  col3  col4  col5
row1     0     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19

In [30]:
df.iloc[1:,2:].values

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [31]:
df.col1.unique()

array([ 0,  5, 10, 15])

In [36]:
df.loc["row1"]["col1"]=5

In [37]:
df

col1  col2  col3  col4  col5
row1     5     1     2     3     4
row2     5     6     7     8     9
row3    10    11    12    13    14
row4    15    16    17    18    19

In [50]:
df[["col4","col5"]]

col4  col5
row1     3     4
row2     8     9
row3    13    14
row4    18    19

In [48]:
type(df.col1)

pandas.core.series.Series

In [38]:
df.col1.unique()

array([ 5, 10, 15])

In [41]:
df.col1.value_counts()

5     2
15    1
10    1
Name: col1, dtype: int64

In [43]:
df.isnull().sum()

col1    0
col2    0
col3    0
col4    0
col5    0
dtype: int64